/* eslint-disable @next/next/no-sync-scripts */
import Document, { Html, Head, Main, NextScript } from "next/document";

class MyDocument extends Document {
  render() {
    return (
      <Html>
        <Head>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link
            crossOrigin="anonymous"
            rel="preconnect"
            href="https://fonts.gstatic.com"
          />
          <link
            href="https://fonts.googleapis.com/css2?family=Abel&display=swap"
            rel="stylesheet"
          />
          <script
            dangerouslySetInnerHTML={{
              __html: `
                (function (sCDN, sCDNProject, sCDNWorkspace, sCDNVers) {
                  if (
                    window.localStorage !== null &&
                    typeof window.localStorage === "object" &&
                    typeof window.localStorage.getItem === "function" &&
                    window.sessionStorage !== null &&
                    typeof window.sessionStorage === "object" &&
                    typeof window.sessionStorage.getItem === "function"
                  ) {
                    sCDNVers =
                      window.sessionStorage.getItem("jts_preview_version") ||
                      window.localStorage.getItem("jts_preview_version") ||
                      sCDNVers;
                  }
                  window.jentis = window.jentis || {};
                  window.jentis.config = window.jentis.config || {};
                  window.jentis.config.frontend = window.jentis.config.frontend || {};
                  window.jentis.config.frontend.cdnhost =
                    sCDN + "/get/" + sCDNWorkspace + "/web/" + sCDNVers + "/";
                  window.jentis.config.frontend.vers = sCDNVers;
                  window.jentis.config.frontend.env = sCDNWorkspace;
                  window.jentis.config.frontend.project = sCDNProject;
                  window._jts = window._jts || [];
                  var f = document.getElementsByTagName("script")[0];
                  var j = document.createElement("script");
                  j.async = true;
                  j.src = window.jentis.config.frontend.cdnhost + "2l12h9.js";
                  f.parentNode.insertBefore(j, f);
                })("https://2jjx7q.anteriam.com","antoni","live", "_");
              
                _jts.push({ track: "pageview" });
                _jts.push({ track: "submit" });
              `,
            }}
          ></script>
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}

export default MyDocument;
